apiVersion: "authentication.istio.io/v1alpha1"
kind: "Policy"
metadata:
  name: "jwt-example"
  namespace: "challengeistio"
spec:
  targets:
  - name: <SERVICENAME>
  origins:
  - jwt:
      issuer: "<ISSUER_STS>"
      jwksUri: "<JWKS_URI>"
  principalBinding: USE_ORIGIN