apiVersion: "v1"
kind: Service
metadata:
  name: sidecarsvc
  labels:
    name: sidecarsvc
    app: sidecar
spec:
  selector:
    name: sidecardemoapibackend
    app: sidecar
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 8080
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sidecardemoapibackend
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: sidecardemoapibackend
        app: sidecar
    spec:
      containers:
      - name: sidecarproxy
        image: csaocpger/aspnetsidecar
        env:
          - name: DEMOAPI_PORT
            value: "80"
          - name: PROXY_PORT
            value: "8080"
        ports:
          - containerPort: 8080
            name: http
            protocol: TCP           
      - name: demoapi
        image: csaocpger/aspnetdemoapi
      imagePullSecrets:
        - name: <secrets>
