apiVersion: "v1"
kind: Service
metadata:
  name: aadpodidentitydemoapisvc
  labels:
    name: aadpodidentitydemoapisvc
    app: aadpodidentitydemoapi
spec:
  selector:
    name: aadpodidentitydemoapibackend
    app: aadpodidentitydemoapi
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: aadpodidentitydemoapibackend
spec:
  replicas: 3
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: aadpodidentitydemoapibackend
        app: aadpodidentitydemoapi
        aadpodidbinding: azureidentitydemo
    spec:
      containers:
      - name: aadpodidentitydemoapi
        image: anmock.azurecr.io/aadpodidentitydemoapi:1.0
        env:
          - name: KeyVault__BaseUrl
            value: "<your keyvault url e.g.: https://myvault.vault.azure.net>"
        ports:
          - containerPort: 80
            name: http
            protocol: TCP 
      imagePullSecrets:
        - name: <your docker-registry secret>