apiVersion: v1
kind: Service
metadata:
  name: quotes-backend
  namespace: challengelinkerd
  labels:
    name: quotes-backend
    app: backend 
spec:
  ports:
  - port: 3000
    name: http
    targetPort: 3000
  selector:
    app: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quotesbackend
  namespace: challengelinkerd
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: quotesbackend
        app: backend
        version: v1
    spec:
      containers:
      - name: calcbackend
        image: csaocpger/quotesbackend:5
        ports:
          - containerPort: 3000
            name: http         
            protocol: TCP
        env: 
          - name: "FAIL_ENABLED"
            value: "0"
          - name: "IMAGE"
            value: "csaocpger/quotesbackend:5"
---
apiVersion: v1
kind: Service
metadata:
  name: quotesgatewaysvc
  namespace: challengelinkerd
  labels:
    name: quotesgatewaysvc
    app: gateway
spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
   - port: 80
     name: http
     targetPort: 3000
     protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: quotesgateway
  namespace: challengelinkerd
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: quotesgateway
        app: gateway
        version: v1
    spec:
      containers:
      - name: quotesgateway
        image: csaocpger/quotesgateway:3
        ports:
        - containerPort: 3000
          name: http         
          protocol: TCP
        env: 
        - name: "GATEWAY_PORT"
          value: "3000"
        - name: "GATEWAY_QUOTES_URL"
          value: "http://quotes-backend:3000/api"