apiVersion: v1
kind: Service
metadata:
  name: calcfrontendsvc
  namespace: challengelinkerd
  labels:
    name: calcfrontendsvc
    app: frontend
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
   - port: 80
     name: http-calcfrontend
     targetPort: 80
     protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jscalcfrontend-v2
  namespace: challengelinkerd
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: jscalcfrontend
        app: frontend
        version: v2
    spec:
      containers:
      - name: jscalcfrontend
        image: csaocpger/jscalcfrontend:5.0
        ports:
          - containerPort: 80
            name: http         
            protocol: TCP
        env: 
          - name: "ENDPOINT"
            value: "calcbackendsvc"
          - name: "PORT"
            value: "80"
---
apiVersion: v1
kind: Service
metadata:
  name: calcbackendsvc
  namespace: challengelinkerd
  labels:
    name: calcbackendsvc
    app: backend 
spec:
  ports:
  - port: 80
    name: http-calcbackend
    targetPort: 80
  selector:
    app: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jscalcbackend-v1
  namespace: challengelinkerd
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: jscalcbackend
        app: backend
        version: v1
    spec:
      containers:
      - name: calcbackend
        image: csaocpger/jscalcbackend:2.0
        ports:
          - containerPort: 80
            name: http         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "80"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gocalcbackend-v1
  namespace: challengelinkerd
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: gocalcbackend
        app: backend
        version: v1
    spec:
      containers:
      - name: gocalcbackend
        image: csaocpger/gocalcbackend:1.0
        ports:
          - containerPort: 80
            name: http         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "80"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: netcorecalcbackend-v1
  namespace: challengelinkerd
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        name: netcorecalcbackend
        app: backend
        version: v1
    spec:
      containers:
      - name: netcorecalcbackend
        image: csaocpger/netcorecalcbackend:1.0
        ports:
          - containerPort: 80
            name: http         
            protocol: TCP
        env: 
          - name: "PORT"
            value: "80"