apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
spec:
  containers:
    - image: vish/stress
      imagePullPolicy: Always
      name: memory-demo-ctr
      args:
        - -cpus
        - "1"
        - -mem-total
        - "600Mi"
        - -mem-alloc-size
        - "10Mi"
        - -mem-alloc-sleep
        - "6s"
